config:
  target: '{{ $env.TEST_SITE_URL }}'
  tls:
    rejectUnauthorized: false
  # Load the Playwright engine:
  engines:
    playwright:
      contextOptions:
        ignoreHTTPSErrors: true
        storageState:
          origins:
          - origin: '{{ $env.TEST_SITE_URL }}'
            localStorage:
            - name: API_HOST
              value: '{{ $env.API_HOST }}'
  processor: './test-functions.js'
  phases:
  - name: initialize
    duration: 30
    arrivalRate: 3
scenarios:
- name: authenticate
  engine: playwright
  testFunction: proxy
