config:
  target: '{{ $env.TEST_SITE_URL }}'
  tls:
    rejectUnauthorized: false
  # Load the Playwright engine:
  engines:
    playwright:
      contextOptions:
        ignoreHTTPSErrors: true
        storageState:
          origins:
          - origin: '{{ $env.TEST_SITE_URL }}'
            localStorage:
            - name: API_HOST
              value: '{{ $env.API_HOST }}'
            - name: sid
              value: '{{ $env.API_HOST }}'
          # cookies:
          # - name: "sid"
          #   value: "12345"
          #   domain: "thailand.pilaproject.org"
          #   path: "/"
          #   httpOnly: true
          #   secure: true
  processor: './test-functions.js'
  phases:
  - name: Load PILA App
    duration: 60
    arrivalRate: 2
scenarios:
- name: Agent Environment Load
  engine: playwright
  testFunction: agentEnvironmentLoad
