config:
  target: '{{ $env.TEST_SITE_URL }}'
  tls:
    rejectUnauthorized: false
  # Load the Playwright engine:
  engines:
    playwright:
      contextOptions:
        ignoreHTTPSErrors: true
        storageState:
          origins:
          - origin: '{{ $env.TEST_SITE_URL }}'
            localStorage:
            - name: api
              value: local
            - name: API_HOST
              value: '{{ $env.API_HOST }}'
  processor: './test-functions.js'
  phases:
    - duration: 30
      arrivalCount: 1000
      maxVusers: 3
scenarios:
  - engine: playwright
    testFunction: 'helloFlow'
