config:
  target: http://localhost:5012
  tls:
    rejectUnauthorized: false
  # Load the Playwright engine:
  engines:
    playwright:
      contextOptions:
        ignoreHTTPSErrors: true
  # Path to JavaScript file that defines Playwright test functions
  processor: './flows.js'
  phases:
    - duration: 30
      arrivalCount: 1000
      maxVusers: 1
scenarios:
  - engine: playwright
    testFunction: 'helloFlow'
